<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
             
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
             
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
             
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
             
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
             
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:

def matrix_mul(A, B):
    
    if len(A[0]) != len(B): return "Not Possible"
    
    newMat = []
    
    for indexA in range(len(A)):
        insideArray = []
        for innerIndexB in range(len(B[0])):
            valSum = 0
            for indexB in range(len(B)):
                valSum = valSum + (A[indexA][indexB]*B[indexB][innerIndexB])
            insideArray.append(valSum)
        newMat.append(insideArray)
    
    return(newMat)

A   = [[1, 2],
        [3, 4]]
             
B   = [[1, 2, 3, 4, 5],
         [5, 6, 7, 8, 9]]
    
matrix_mul(A, B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform

def pick_a_number_from_list(A):
    sumVal = 0
    for ele in A:
        sumVal += ele
    cumsum = 0
    listOfCumsum = []
    for val in A:
        tillNowCumsum = cumsum+(val/sumVal)
        listOfCumsum.append(tillNowCumsum)
        cumsum = tillNowCumsum
    randomVal = uniform(0.0, 1.0)
    for i in range(0, len(listOfCumsum)):
        if randomVal >= listOfCumsum[i] and randomVal < listOfCumsum[i+1]:
            return A[i+1]

def sampling_based_on_magnitued():
    A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

27
100
79
79
10
45
13
79
27
100
5
13
28
100
100
79
27
100
100
79
28
79
79
10
79
79
79
79
100
100
100
45
100
79
6
10
10
79
100
100
28
27
79
100
79
100
79
100
45
27
28
100
79
100
79
100
100
100
13
100
79
27
100
45
100
79
79
79
28
100
79
10
10
100
45
45
100
79
10
10
28
100
27
79
10
28
79
79
45
45
100
45
100
100
100
6
100
13
45


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re

def replace_digits(String):
    for i in re.findall(r'\d', String):
        hashVal = print("#", end="")
    return(hashVal)

String = "#2a$#b%c%561#"
replace_digits(String)

####

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:

def display_dash_board(students, marks):
    
    studentMarks = dict()
    for i in range(len(students)):
        studentMarks[students[i]] = marks[i]
        
    # top 5 students
    
    top_marks = sorted(studentMarks.values())[:4:-1]
    top_5_students = dict()
    for m in top_marks:
        for student, t_marks in studentMarks.items():
            if t_marks == m:
                top_5_students[student] = t_marks
    
    # top least 5 students
    
    least_marks = sorted(studentMarks.values())[:5]
    least_5_students = dict()
    for l in least_marks:
        for student, l_marks in studentMarks.items():
            if l_marks == l:
                least_5_students[student] = l_marks
    
    # students_within_25_and_75 percentile

    percentile_25 = len(students)*(25/100)
    percentile_75 = len(students)*(75/100)
    students_within_25_and_75 = dict()
    stu_25_75 = sorted(studentMarks.values())[(round(percentile_25)):round(percentile_75)-1]
    for p in stu_25_75:
        for student, p_marks in studentMarks.items():
            if p_marks == p:
                students_within_25_and_75[student] = p_marks
    
    return top_5_students, least_5_students, students_within_25_and_75


Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)

print("a.", end="\n")
for key, value in top_5_students.items():
    print(key, " ", value)
print("b.", end="\n")
for key, value in least_5_students.items():
    print(key, " ", value)
print("c.", end="\n")
for key, value in students_within_25_and_75.items():
    print(key, " ", value)

a.
student8   98
student10   80
student2   78
student5   48
student7   47
b.
student3   12
student4   14
student9   35
student6   43
student1   45
c.
student9   35
student6   43
student1   45
student7   47
student5   48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

def closest_points_to_p(S, P):
    distancesOfPoints = []
    mergeTup = {}
    closest_points_to_p = []
    for tup in S:
        dist = math.acos(((tup[0]*P[0])+(tup[1]*P[1]))/((math.sqrt(pow(tup[0], 2)+pow(tup[1], 2)))*(math.sqrt(pow(P[0], 2)+pow(P[1],2)))))
        distancesOfPoints.append(dist)
    for i in range(len(distancesOfPoints)):
        mergeTup[distancesOfPoints[i]] = S[i]
    for k in sorted(mergeTup.keys())[:5]:
        for key, value in mergeTup.items():
            if key == k:
                closest_points_to_p.append(value)
    return closest_points_to_p

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
for p in points:
    print(p)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:

def point_product(a, b, c, tup1, tup2):
  x1, y1 = tup1
  x2, y2 = tup2
  fx1 = (a*int(x1)) + (b*int(y1)) + c
  fx2 = (a*int(x2)) + (b*int(y2)) + c
  if int(fx1 * fx2) >= 0:
    return True
  else:
    return False

def i_am_the_one(red,blue,line):
  result = False
  a, b, c = re.split('x|y', line)
  for r in red:
    for bl in blue:
      result = point_product(float(a), float(b), float(c), r, bl)
      if result:
        result = True
      else:
        result = False
        break
    break
  if result:
    return "No"
  else:
    return "Yes"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no)

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:

def curve_smoothing(string):
    split_string = string.split(',')
    countSpace = 0
    initial = 0
    initialindex = 0
    lastindex = 0
    for i, ele in enumerate(split_string):
        if ele == "_":
            countSpace += 1
            lastindex = i+1
            if i == len(split_string)-1:
                divide = initial/(countSpace)
                split_string[initialindex:lastindex] = countSpace * [str(int(divide))]
                countSpace = 1
                initial = int(divide)
                initialindex = i
        else:
          if i == len(split_string)-1:
              divide = (initial+int(ele))/(countSpace+1)
              split_string[initialindex:lastindex+1] = (countSpace+1) * [str(int(divide))]
              countSpace = 1
              initial = int(divide)
              initialindex = i
          else:
              divide = (initial+int(ele))/(countSpace+1)
              split_string[initialindex:lastindex] = countSpace * [str(int(divide))]
              countSpace = 1
              initial = int(divide)
              initialindex = i
    return split_string

S=  "_,_,30,_,_,_,50,_,_"

smoothed_values= curve_smoothing(S)
print(",".join(smoothed_values))

10,10,12,12,12,12,4,4,4


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
def print_func(A, fIndex, Sindex, Sdict):
  count = 0
  for row in A:
    if row[0] == 'F'+str(fIndex) and row[1] == 'S'+str(Sindex):
      count += 1
  return ("Probability of P(F" + str(fIndex) + "|S" + str(Sindex) + ")" + " = " + str(count) + "/" + str(Sdict['S' + str(Sindex)]))

def compute_conditional_probabilites(A):
    Sdict = dict()
    for row in A:
      a = Sdict.get(row[1], 0)
      Sdict[row[1]] = a + 1
    for f in range(1,6):
      fString = ''
      for s in range(1, 4):
        pString = print_func(A, f, s, Sdict)
        if s == 3:
          print(pString)
        else:
          print(pString, end=", ")
      fString = pString
      print("",end="\n")


A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

Probability of P(F1|S1) = 1/4, Probability of P(F1|S2) = 1/3, Probability of P(F1|S3) = 0/3

Probability of P(F2|S1) = 1/4, Probability of P(F2|S2) = 1/3, Probability of P(F2|S3) = 1/3

Probability of P(F3|S1) = 0/4, Probability of P(F3|S2) = 1/3, Probability of P(F3|S3) = 1/3

Probability of P(F4|S1) = 1/4, Probability of P(F4|S2) = 0/3, Probability of P(F4|S3) = 1/3

Probability of P(F5|S1) = 1/4, Probability of P(F5|S2) = 0/3, Probability of P(F5|S3) = 0/3



<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:

def string_features(S1, S2):
    s1_dict = dict() 
    s2_dict = dict()
    a = 0
    b = []
    c = []

    # S1 dict
    for s in S1.split(" "):
      ind = s1_dict.get(s, 0)
      s1_dict[s] = ind + 1
    
    # S2 dict
    for s in S2.split(" "):
      ind = s2_dict.get(s, 0)
      s2_dict[s] = ind + 1

      # c point calculation
      i = s1_dict.get(s, -1)
      if i == -1:
        c.append(s)
    
    # a and b point calculation
    for ele in S1.split(" "):
      i = s2_dict.get(ele, -1)
      if i != -1:
        a += 1
      else:
        b.append(ele)
    
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(" a.", a, "\n", "b.", b, "\n", "c. ", c)

 a. 7 
 b. ['first', 'F', '5'] 
 c.  ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
def compute_sum(eleList):
  y = eleList[0]
  y_score = eleList[1]
  innerSum = ( (y*math.log10(y_score)) + ((1-y)*(math.log10(1-y_score))))
  return innerSum

def compute_log_loss(A):
  summation = 0
  loss = 0
  for ele in A:
    summation += compute_sum(ele)
    loss = summation * (-1/len(A))
  return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print('{0:.7f}'.format(loss))

0.4243099
